### ISSUE TITLE
Controller has no method update

### ISSUE THREAD

**Issue by cra1gs** [FokkeZB/nl.fokkezb.loading#26]
I am sure this is something I have done incorrectly. So is it possible to see an example of update please?

I am using the below

Alloy.Globals.loading.show('Loading...', false);

Alloy.Globals.loading.update('new text', false);

But I get the error:
Message: Uncaught TypeError: Object #<Controller> has no method 'update'

Thanks

**Comment by FokkeZB** [comment]
I've updated the readme to inform you that `update()` is not available in global-mode. Simply call `show()` again.

**Comment by cra1gs** [comment]
Thanks. I didn't think to try that.
