### ISSUE TITLE
undefined is not an object (evaluating 'Ti.UI.ActivityIndicatorStyle.BIG')

### ISSUE THREAD

**Issue by jmcerrejon** [FokkeZB/nl.fokkezb.loading#29]
I recently update to 1.8.4
I'm using global var with *SDK 5.0.2* in *alloy.js*

When I fire the *Alloy.Globals.loading.show('Checking...', false)* I get the next error message:
**undefined is not an object (evaluating 'Ti.UI.ActivityIndicatorStyle.BIG')**

I saw in the *view.tss* the code:
 ".loadingIndicator": {
  top: '0dp',
  style: Ti.UI.ActivityIndicatorStyle.BIG
}

If I remove the *style*, It works.

**Comment by FokkeZB** [comment]
`Titanium.UI.iPhone.ActivityIndicatorStyle` has been replaced by `Titanium.UI.ActivityIndicatorStyle` in Titanium 5.1 and I updated the widget accordingly. If you need to use an older SDK just use a theme to override with the old namespace or in `app.tss` use:

```
"#loadingIndicator": {
  style: Ti.UI.iPhone.ActivityIndicatorStyle.BIG
}
```
