### ISSUE TITLE
Android - Force the colour of the spinner

### ISSUE THREAD

**Issue by clementblanco** [FokkeZB/nl.fokkezb.loading#35]
When you using the global loading functionality on Android `Alloy.Globals.loading.show();` it doesn't get styled using the theme and the spinner is using the default colour from Android 6.0 OS (greenish).

How to change this to another colour? Using theming? Would you know which property exactly?
Is there a way to force all the activity indicators to look the same within my application?

Only if I use the non-global way using a `<Widget/>` within my view `$.loading.show();` the ActivityIndicator will be styled according to the value of my `colorAccent` attrbitute within `platform/android/res/values/custom_theme.xml`.

**Comment by FokkeZB** [comment]
Mmm, there should be no difference between using the view or global mode. Do you have a complete example?
