### ISSUE TITLE
iOS could not find module

### ISSUE THREAD

**Issue by odahcam** [FokkeZB/nl.fokkezb.loading#41]
Widget version: 1.8.4
Alloy: 1.9
Ti SDK: 6.0.4.GA

![image](https://cloud.githubusercontent.com/assets/3942006/26469913/1988f18e-4172-11e7-8947-974c306e1432.png)

**Comment by FokkeZB** [comment]
@odahcam thx for reporting!

Could you check your `Resources` folder to see if `/ios/alloy/widgets/nl.fokkezb.loading/controllers/progress.js` is there?

**Comment by odahcam** [comment]
It is not there, there is only 3 files:
* view.js
* widget.js
* window.js

**Comment by FokkeZB** [comment]
That makes sense since progress is an Android only view, sorry for asking the obvious ;)

What is the code you use to use the widget?

**Comment by odahcam** [comment]
![image](https://cloud.githubusercontent.com/assets/3942006/26506622/acdbdd78-4223-11e7-85a6-f5d5b729e885.png)

**Comment by FokkeZB** [comment]
Yep, indeed! As https://github.com/FokkeZB/nl.fokkezb.loading#native-progress-android-only says that's Android only.

**Comment by odahcam** [comment]
It's not much usual, I thought that this "switch" was automatic. What happens if I don't pass any arguments in this parameter?

**Comment by FokkeZB** [comment]
If you don't pass the second argument, it will default to the `widget` controller.

You can simply do:

```js
var ActivityIndicator = Alloy.createWidget('nl.fokkezb.loading', OS_IOS ? 'window' : 'progress');
```

**Comment by odahcam** [comment]
That's exactly what I did, so it is the best approach to multiplatform apps?

**Comment by FokkeZB** [comment]
Definitely
